export const FONT =
  "'Noto Sans JP', 'Hiragino Kaku Gothic ProN', 'Yu Gothic', sans-serif";

export const S = {
  root: {
    fontFamily: FONT,
    background: "#f8fafc",
    minHeight: "100vh",
    color: "#1e293b",
    fontSize: 14,
    lineHeight: 1.6,
  },
  loadWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
  },
  loadSpin: {
    width: 32,
    height: 32,
    border: "3px solid #e2e8f0",
    borderTop: "3px solid #2563eb",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  header: {
    background:
      "linear-gradient(135deg, #1e3a5f 0%, #1e40af 50%, #1d4ed8 100%)",
    padding: "20px 24px",
    color: "#fff",
  },
  headerInner: { maxWidth: 960, margin: "0 auto" },
  logo: { display: "flex", alignItems: "center", gap: 14 },
  logoMark: {
    width: 44,
    height: 44,
    background: "rgba(255,255,255,0.15)",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    fontWeight: 800,
  },
  logoTitle: { margin: 0, fontSize: 20, fontWeight: 700, letterSpacing: "0.02em" },
  logoSub: { margin: 0, fontSize: 12, opacity: 0.8 },
  nav: {
    background: "#fff",
    borderBottom: "1px solid #e2e8f0",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  navScroll: {
    maxWidth: 960,
    margin: "0 auto",
    display: "flex",
    gap: 2,
    padding: "0 8px",
    overflowX: "auto",
  },
  navBtn: {
    padding: "10px 10px",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    fontSize: 12,
    color: "#64748b",
    display: "flex",
    alignItems: "center",
    gap: 4,
    whiteSpace: "nowrap",
    borderBottom: "2px solid transparent",
    transition: "all 0.15s",
    fontFamily: FONT,
  },
  navBtnActive: { color: "#1d4ed8", borderBottomColor: "#1d4ed8", fontWeight: 600 },
  main: { maxWidth: 960, margin: "0 auto", padding: "24px 16px" },
  card: {
    background: "#fff",
    borderRadius: 12,
    padding: "20px 24px",
    marginBottom: 16,
    border: "1px solid #e2e8f0",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  cardTitle: { margin: "0 0 16px", fontSize: 15, fontWeight: 700, fontFamily: FONT },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    gap: 8,
    margin: 0,
    fontFamily: FONT,
  },
  sectionSub: { fontSize: 13, fontWeight: 400, color: "#94a3b8", marginLeft: 8 },
  dashGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: 12,
    marginBottom: 16,
  },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  formGroup: { display: "flex", flexDirection: "column", gap: 4, marginBottom: 8 },
  label: { fontSize: 12, fontWeight: 600, color: "#475569", fontFamily: FONT },
  input: {
    padding: "9px 12px",
    border: "1px solid #d1d5db",
    borderRadius: 8,
    fontSize: 14,
    outline: "none",
    fontFamily: FONT,
    width: "100%",
    boxSizing: "border-box",
  },
  formActions: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 16 },
  btnPrimary: {
    padding: "10px 28px",
    background: "#1d4ed8",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONT,
  },
  btnSecondary: {
    padding: "10px 20px",
    background: "#fff",
    color: "#475569",
    border: "1px solid #d1d5db",
    borderRadius: 8,
    fontSize: 14,
    cursor: "pointer",
    fontFamily: FONT,
  },
  msg: { textAlign: "center", marginTop: 12, fontSize: 14, fontWeight: 500 },
  presetLabel: { margin: "0 0 8px", fontSize: 12, color: "#64748b", fontWeight: 600 },
  presetWrap: { display: "flex", flexWrap: "wrap", gap: 6 },
  presetBtn: {
    padding: "5px 12px",
    border: "1px solid #e2e8f0",
    borderRadius: 20,
    background: "#f8fafc",
    fontSize: 12,
    color: "#475569",
    cursor: "pointer",
    fontFamily: FONT,
  },
  easyCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 16px",
    border: "1px solid #e2e8f0",
    borderRadius: 10,
    background: "#fff",
    cursor: "pointer",
    textAlign: "left",
    fontFamily: FONT,
    transition: "all 0.15s",
    boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
  },
  payBtn: {
    padding: "8px 16px",
    border: "1px solid #d1d5db",
    borderRadius: 8,
    background: "#fff",
    cursor: "pointer",
    fontSize: 13,
    fontFamily: FONT,
  },
  payBtnActive: {
    background: "#eff6ff",
    borderColor: "#3b82f6",
    color: "#1d4ed8",
    fontWeight: 600,
  },
  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    textAlign: "left",
    padding: "10px 12px",
    fontSize: 12,
    fontWeight: 600,
    color: "#64748b",
    borderBottom: "2px solid #e2e8f0",
    fontFamily: FONT,
  },
  tr: { borderBottom: "1px solid #f1f5f9" },
  totalRow: { borderTop: "2px solid #e2e8f0", background: "#f8fafc" },
  td: { padding: "10px 12px", fontSize: 13, fontFamily: FONT },
  tblBtn: {
    background: "none",
    border: "none",
    color: "#2563eb",
    cursor: "pointer",
    fontSize: 12,
    padding: "2px 6px",
    fontFamily: FONT,
  },
  footer: {
    textAlign: "center",
    padding: "24px 16px",
    color: "#94a3b8",
    fontSize: 11,
    fontFamily: FONT,
  },
};
